version: "3.9"

services:
  db:
    image: postgres:17
    container_name: apontamentos-db
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
