"""baseline

Revision ID: d2fbb0ae9bbd
Revises:
Create Date: 2025-08-23 18:42:59.590808

"""

# revision identifiers, used by Alembic.
revision = "d2fbb0ae9bbd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
