"""baseline

Revision ID: d2fbb0ae9bbd
Revises:
Create Date: 2025-08-23 18:42:59.590808

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d2fbb0ae9bbd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
