name: Deploy to Production

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE: ghcr.io/${{ github.repository }}
  PUBLIC_HEALTH_URL: https://api-apontamentos.pedroct.com.br/healthz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Autentica no GHCR usando o GITHUB_TOKEN (escopo packages:write já definido)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build & Push image
        run: |
          docker build -t "${IMAGE}:${GITHUB_SHA}" -t "${IMAGE}:latest" .
          docker push "${IMAGE}:${GITHUB_SHA}"
          docker push "${IMAGE}:latest"

      # (Opcional porém recomendado) fixa host key antes de conectar
      - name: Cache server host key (port 2222)
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p 2222 "api-apontamentos.pedroct.com.br" >> ~/.ssh/known_hosts

      - name: Check SSH connectivity (TCP 2222)
        run: |
          set -euxo pipefail
          getent ahostsv4 "api-apontamentos.pedroct.com.br" || true
          # tenta TCP connect (10s) na 2222
          timeout 10 bash -c "exec 3<>/dev/tcp/api-apontamentos.pedroct.com.br/2222" && echo "TCP 2222 open"

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: api-apontamentos.pedroct.com.br #${{ secrets.SSH_HOST }}          # 201.51.130.202
          username: pedroct                      # ou ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}       # chave privada correspondente ao authorized_keys no servidor
          port: 2222                             # DNAT no Mikrotik -> 192.168.1.158:22
          timeout: 2m
          command_timeout: 15m
          script: |
            set -euo pipefail
            APP_DIR="/home/pedroct/apps/apontamentos-api"

            # Login no GHCR dentro do servidor para puxar as imagens
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            cd "$APP_DIR"
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f

            # Health local do backend (ajuste porta/path se necessário)
            for i in {1..30}; do
              curl -fsS http://127.0.0.1:8000/healthz && break || sleep 2
            done

      - name: Public smoke test (HTTPS)
        run: |
          for i in {1..30}; do
            code=$(curl -sk -o /dev/null -w "%{http_code}" "${PUBLIC_HEALTH_URL}")
            if [ "$code" = "200" ]; then
              echo "OK ${PUBLIC_HEALTH_URL}"
              curl -fsS "${PUBLIC_HEALTH_URL}"
              exit 0
            fi
            sleep 2
          done
          echo "Falha no smoke test público em ${PUBLIC_HEALTH_URL}"
          exit 1
