name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Vars
        id: v
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
          echo "TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t ${{ steps.v.outputs.IMAGE }}:${{ steps.v.outputs.TAG }} .
          docker tag  ${{ steps.v.outputs.IMAGE }}:${{ steps.v.outputs.TAG }} ${{ steps.v.outputs.IMAGE }}:latest

      - name: Push
        run: |
          docker push ${{ steps.v.outputs.IMAGE }}:${{ steps.v.outputs.TAG }}
          docker push ${{ steps.v.outputs.IMAGE }}:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}   # ex.: pedroct
          key: ${{ secrets.SSH_KEY }}
          script: |
            REPO="$(basename $GITHUB_REPOSITORY)"
            APP_DIR="/home/pedroct/apps/$REPO"
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            cd "$APP_DIR"
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
